package datalab.upo.ladonspark.model;
// Generated 07-jun-2018 9:12:05 by Hibernate Tools 4.3.1



/**
 * Parameter generated by hbm2java
 */
public class Parameter  implements java.io.Serializable {


     private Integer idPar;
     private Algorithm algorithm;
     private String namePar;
     private String typePar;

    public Parameter() {
    }

    public Parameter(Algorithm algorithm, String namePar, String typePar) {
       this.algorithm = algorithm;
       this.namePar = namePar;
       this.typePar = typePar;
    }
   
    public Integer getIdPar() {
        return this.idPar;
    }
    
    public void setIdPar(Integer idPar) {
        this.idPar = idPar;
    }
    public Algorithm getAlgorithm() {
        return this.algorithm;
    }
    
    public void setAlgorithm(Algorithm algorithm) {
        this.algorithm = algorithm;
    }
    public String getNamePar() {
        return this.namePar;
    }
    
    public void setNamePar(String namePar) {
        this.namePar = namePar;
    }
    public String getTypePar() {
        return this.typePar;
    }
    
    public void setTypePar(String typePar) {
        this.typePar = typePar;
    }




}


