package datalab.upo.ladonspark.model;
// Generated 07-jun-2018 9:12:05 by Hibernate Tools 4.3.1



/**
 * Parameter generated by hbm2java
 */
/*
* This file is part of LadonSpark.

* LadonSpark is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.

* LadonSpark is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.

* You should have received a copy of the GNU General Public License
* along with LadonSpark.  If not, see <https://www.gnu.org/licenses/>.
*/
public class Parameter  implements java.io.Serializable {


     private Integer idPar;
     private Algorithm algorithm;
     private String namePar;
     private String typePar;

    public Parameter() {
    }

    public Parameter(Algorithm algorithm, String namePar, String typePar) {
       this.algorithm = algorithm;
       this.namePar = namePar;
       this.typePar = typePar;
    }
   
    public Integer getIdPar() {
        return this.idPar;
    }
    
    public void setIdPar(Integer idPar) {
        this.idPar = idPar;
    }
    public Algorithm getAlgorithm() {
        return this.algorithm;
    }
    
    public void setAlgorithm(Algorithm algorithm) {
        this.algorithm = algorithm;
    }
    public String getNamePar() {
        return this.namePar;
    }
    
    public void setNamePar(String namePar) {
        this.namePar = namePar;
    }
    public String getTypePar() {
        return this.typePar;
    }
    
    public void setTypePar(String typePar) {
        this.typePar = typePar;
    }




}


